<?php
/**
 * Created by PhpStorm.
 * User: robbert
 * Date: 31-1-17
 * Time: 0:00
 */

/**
 * Alle listings in MCM, om links te kunnen maken naar files op de disk
 *
 * 1: het bladnummer (dus NIET het nummer van de disk, dat is meestal 1 lager
 * 2: het paginanummer (van de eerste regel van de listing) of 0 als listing niet in blad staat
 * 3: de filenaam van het bestand op de disk
 * 4: de naam in leesbare vorm (titel van het artikel, opschrijving op disk)
 * 5: minimale MSX versie nodig (1: MSX1, 2: MSX2, 3: MSX2+)
 *
 */
$mcm_listings = array(
    array(1, 18, 'invoerco', 'Invoer Controle Programma', 1),
    array(1, 40, 'lampjes', 'Lampjes', 1),
    array(1, 42, 'botsauto', 'Botsauto\'s', 1),
    array(1, 46, 'blue&pin', 'Schuifpuzzel Blue & Pink', 1),
    array(1, 48, 'wijnglas', 'Tweedimensionaal Wijnglas', 1),

    array(2, 6, 'invoer', 'Invoer Controle Programma 2', 1),
    array(2, 51, 'gokkast', 'Gokmachine', 1),
    array(2, 54, 'appel', 'Appel', 1),

    array(3, 9, 'invoer', 'Invoer Controle Programma 2', 1),
    array(3, 14, 'k&k3-1', 'Kleurenschijf', 1),
    array(3, 14, 'k&k3-2', 'Mondriaan', 1),
    array(3, 15, 'k&k3-3', 'Stralen', 1),
    array(3, 15, 'k&k3-4', 'Ballentent', 1),
    array(3, 15, 'k&k3-5', 'Toonladders', 1),
    array(3, 28, 'sprite', 'Sprite-editor', 1),
    array(3, 33, 'basdis', 'BasDis', 1),
    array(3, 38, 'planet', 'Planetarium', 1),
    array(3, 42, 'bronsk', 'Bronski', 1),
    array(3, 44, 'msxtyp', 'MSX Type', 1),
    array(3, 54, 'ufo', 'UFO', 1),
    array(3, 55, 'copy', 'Copyfile', 1),
    array(3, 57, 'crtdmp', 'CRT dump', 1),
    array(3, 0, 'woord', 'Galgje', 1), // heeft cassette nodig?
    array(3, 0, 'woordh', 'Hulpje voor Galgje', 1),
    array(3, 0, 'benelu', 'Benelux kaart', 1),
    array(3, 0, 'yathze', 'Yathzee', 1),
    array(3, 0, 'f(x)', 'Wiskunde', 1),

    array(4, 9, 'icp3', 'Invoer Controle Programma 3', 1),
    array(4, 34, 'remsp', 'Rem Space Killer', 1),
    array(4, 40, 'msxpen', 'MSX Pen', 1),
    array(4, 48, 'escape', 'Escape', 1),
    array(4, 51, 'kerkkl', 'Kerkklok', 1),
    array(4, 52, 'lockin', 'Lockin\' Man', 1),
    array(4, 54, 'vsteke', 'VSTEKE', 1),
    array(4, 58, 'klad', 'Kladblok', 1),
    array(4, 63, 'k&k4-1', 'Kleurenschijf', 1),
    array(4, 63, 'k&k4-2', 'Kleurenschijf', 1),
    array(4, 63, 'k&k4-3', 'Lijnenshow', 1),
    array(4, 63, 'k&k4-4', 'Tekens', 1),
    array(4, 64, 'k&k4-5', 'Toetsenbord-muziek', 1),
    array(4, 75, 'lhl4-1', 'Plotter-Screendump 1', 1),
    array(4, 75, 'lhl4-2', 'Plotter-Screendump 2', 1),
    array(4, 75, 'lhl4-3', 'Bridge-oefen programma', 1),
    array(4, 0, 'myster', 'Mystery Town (adventure)', 1),
    array(4, 0, 'horror', 'Horror', 1),

    array(5, 7, 'icp3', 'Invoer Controle Programma 3', 1),
    array(5, 29, 'schat', 'Schatten duiken', 1),
    array(5, 31, 'snelli', 'Snelli', 1),
    array(5, 32, 'beurs', 'Beurs-spel', 1),
    array(5, 34, 'tapdir', 'Tapdir', 1),
    array(5, 36, 'letter', 'Letter', 1),
    array(5, 38, 'dskmon', 'Diskmonitor', 1),
    array(5, 40, 'grolet', 'Grolet', 1),
    array(5, 45, 'tips85', 'Tips85', 1),

    array(5, 48, 'k&k5-1', 'Op z\'n kop', 1),
    array(5, 48, 'k&k5-2', 'Op z\'n kop', 1),
    array(5, 48, 'k&k5-3', 'Op z\'n kop', 1),
    array(5, 48, 'k&k5-4', 'Spriraal', 1),
    array(5, 48, 'k&k5-5', 'Cirkels', 1),
    array(5, 49, 'k&k5-6', 'Lichtkrant oneliner', 1),
    array(5, 49, 'k&k5-7', 'lichtkrant', 1),
    array(5, 49, 'k&k5-8', 'Vader Jacob', 1),
    array(5, 56, 'trk5-1', 'Stoppen anders', 1),
    array(5, 56, 'trk5-2', 'Vader Jacob', 1),

    array(5, 0, 'tapdir', 'Tapdir', 1),
    array(5, 0, 'dolen', 'Doolhof', 1),
    array(5, 0, 'xytest', 'Vindt uw korrektie', 1),
    array(5, 0, 'bach', 'Orgelmuziek', 1),
    array(5, 0, 'reuter', 'Onmogelijke driehoek', 1),

    array(6, 6, 'icp3', 'Invoer Controle Programma 3', 1),
    array(6, 14, 'bubble', 'Bubble-sort', 1),
    array(6, 16, 'shell', 'Shell-sort', 1),
    array(6, 18, 'numsrt', 'Test sorteermethodes numeriek', 1),
    array(6, 18, 'alfsrt', 'Test sorteermethodes alfabetisch', 1),
    array(6, 19, 'srttim', 'Timing sorteermethodes', 1),
    array(6, 36, 'edit', 'Edit', 1),
    array(6, 39, 'colors', 'Colors', 2),
    array(6, 45, 'figrek', 'Figrek', 1),
    array(6, 48, 'memmon', 'Memmon', 1),
    array(6, 49, '3ddes', '3D-des', 1),
    array(6, 56, 'mlvb01', 'Werken met ML voorbeeld 1', 1),
    array(6, 56, 'mlvb02', 'Werken met ML voorbeeld 2', 1),
    array(6, 0, 'snake3', 'Snake 3', 1),

    array(7, 6, 'icp3', 'Invoer Controle Programma 3', 1),
    array(7, 20, 'k&k7-1', 'Inverse tekens', 1),
    array(7, 20, 'k&k7-2', 'Kleurrijk 1', 1),
    array(7, 20, 'k&k7-3', 'Kleurrijk 2', 1),
    array(7, 21, 'k&k7-4', 'Kleurrijk 3', 1),
    array(7, 21, 'k&k7-5', 'Lichtkrant', 1),
    array(7, 21, 'k&k7-6', 'Lichtkrant oneliner', 1),
    array(7, 29, 'mlvb03', 'Cursus Z80 machinetaal voorbeeld 3', 1),
    array(7, 31, 'sbvb01', 'Omrekentabellen dec/bin/hex', 1),
    array(7, 40, 'dsktyp', 'DSKTYP', 1),
    array(7, 60, 'lhl7-1', 'Autostart ML', 1),
    array(7, 61, 'lhl7-2', 'Autostart Basic', 1),
    array(7, 61, 'lhl7-3', 'Knight rider sound', 1),
    array(7, 64, 'typles', 'TYPLES', 1),
    array(7, 69, 'varlst', 'VARLST', 1),
    array(7, 69, 'linlst', 'LINLST', 1),
    array(7, 73, 'alien', 'Alien', 1),
    array(7, 76, 'vissen', 'Vissen', 1),
    array(7, 0, 'phlps2', 'Philips MSX2 demo 1', 2),
    array(7, 0, 'phlps1', 'Philips MSX2 demo 2', 2),

    array(8, 11, 'k&k8-0', 'Klick => Beep', 1),
    array(8, 11, 'k&k8-1', 'Vlak na vlak', 1),
    array(8, 11, 'k&k8-2', 'Vierkanten', 1),
    array(8, 11, 'k&k8-3', 'Kleurige Cirkels', 1),
    array(8, 11, 'k&k8-4', 'Lijnfiguur', 1),
    array(8, 11, 'k&k8-5', 'Lopende functietoetsen', 1),
    array(8, 11, 'k&k8-6', 'Tropische verrassingen', 1),
    array(8, 11, 'k&k8-7', 'Tropische verrassingen aangepast', 1),
    array(8, 11, 'k&k8-8', 'Stilstaande kantlijn', 1),
    array(8, 11, 'k&k8-9', 'Stilstaande kantlijn aangepast', 1),
    array(8, 19, 'ctrlpl', 'CTRLP screendump in ML', 1),
    array(8, 19, 'ctrlpk', 'CTRLP screendump in ML uitgebreid', 1),
    array(8, 24, 'snabar', 'Snackbar', 1),
    array(8, 36, 'ml04', 'Cursus Z80 machinetaal voorbeeld 4', 1),
    array(8, 36, 'ml05', 'Cursus Z80 machinetaal voorbeeld 5', 1),
    array(8, 36, 'ml06', 'Cursus Z80 machinetaal voorbeeld 6', 1),
    array(8, 55, 'digklk', 'beschrijving', 1),
    array(8, 59, 'space', 'Space-walk', 1),
    array(8, 64, 'dskidx', 'DSKIDX', 1),
    array(8, 0, 'qbert', 'QBERT', 1),
    array(8, 0, 'icp3', 'Invoer Controle Programma 3', 1),

    array(9, 7, 'icp4', 'Invoer Controle Programma 4', 1),
    array(9, 54, 'varln2', 'Varln 2', 1),
    array(9, 59, 'msxprt', 'MSXPRT', 1),
    array(9, 61, 'supdir', 'Supdir', 1),
    array(9, 0, 'topgra', 'Topografie', 1),
    array(9, 0, 'tellen', 'Tellen', 1),
    array(9, 0, 'tafels', 'Tafels', 1),
    array(9, 0, 'trein', 'Trein', 1),
    array(9, 0, 'wammes.sc8', 'Portret Wammes Witkop', 2),
    array(9, 0, 'ldsc8', 'Kleurenfoto MSX2', 2),

    array(10, 6, 'icp4', 'Invoer Controle Programma 4', 1),
    array(10, 20, 'break', 'Break', 1),
    array(10, 27, 'ml10-1', 'Cursus Z80 machinetaal voorbeeld Mooi', 1),
    array(10, 27, 'ml10-2', 'Cursus Z80 machinetaal voorbeeld Simpel', 1),
    array(10, 27, 'ml10-3', 'Cursus Z80 machinetaal voorbeeld laatste', 1),
    array(10, 27, 'ml10-4', 'Cursus Z80 machinetaal voorbeeld Basic loader', 1),
    array(10, 30, 'drum', 'Drum', 1),
    array(10, 36, 'reflst', 'REFLST', 1),
    array(10, 56, 'repwek', 'Repwek', 1),
    array(10, 61, 'linklk', 'Linklk', 1),
    array(10, 62, 'watklk', 'Watklk', 1),
    array(10, 0, 'kk10-1', 'De Wip', 2),
    array(10, 0, 'kk10-2', 'Mondriaan', 2),
    array(10, 0, 'kk10-3', 'Schillen 1', 2),
    array(10, 0, 'kk10-4', 'Schillen 2', 2),
    array(10, 0, 'kk10-5', 'Driehoek', 2),
    array(10, 0, 'kk10-6', 'Palet', 2),
    array(10, 0, 'kk10-7', 'Hypno', 2),

    array(10, 0, 'adelin', 'Repwek-melodie Adelin', 1),
    array(10, 0, 'menuet', 'Repwek-melodie Menuet', 1),
    // array(10, 0, 'mcmd9', 'beschrijving', 1), // het menu
    array(10, 0, 'supmrg', 'Supdir-reparatie', 1),

    array(11, 8, 'icp4', 'Invoer Controle Programma 4', 1),
    array(11, 12, 'joysor', 'Joysor', 1),
    array(11, 41, 'strkls', 'Strkls', 1),
    array(11, 53, 'keuken', 'Keuken', 1),
    array(11, 64, 'sclptr', 'Sclptr', 1),
    array(11, 0, 'sprite', 'Sprite', 1),

    array(12, 8, 'icp4', 'Invoer Controle Programma 4', 1),
    array(12, 12, 'ml09', 'Cursus Z80 machinetaal voorbeeld 9', 1),
    array(12, 22, 'pucky', 'Pucky', 1),
    array(12, 33, 'tstbld', 'Testbeeld', 2),
    array(12, 35, 'msxmem', 'MSXmem', 1),
    array(12, 40, 'teller', 'Teller', 1),
    array(12, 0, 'begadr', 'BEGADR (begin-, eind- en start-adressen)', 1),
    array(12, 0, 'kerst', 'Kerstwens', 1),

    array(13, 8, 'icp4', 'Invoer Controle Programma 4', 1),
    array(13, 24, 'insert', 'Insertion sort', 1),
    array(13, 24, 'bubble', 'Bubble sort', 1),
    array(13, 25, 'shell', 'Shell sort', 1),
    array(13, 25, 'smsort', 'Shell-Metzner sort', 1),
    array(13, 27, 'srttm2', 'Timing sorteer-methodes', 1),
    array(13, 29, 'print', 'Print', 1),
    array(13, 32, 'salber', 'Salber', 1),
    array(13, 56, 'jake', 'Jake', 1),
    array(13, 0, 'belain', 'Belastingprogramma Intro', 1),
    array(13, 0, 'bela40', 'Belastingprogramma 40 kolommen', 1),
    array(13, 0, 'bela80', 'Belastingprogramma 80 kolommen', 2),

    array(14, 8, 'icp4', 'Invoer Controle Programma 4', 1),
    array(14, 11, 'alg31', 'Lineaire search', 1),
    array(14, 12, 'alg32', 'Demo Lineaire search', 1),
    array(14, 13, 'alg33', 'Demo gesorteerd Lineaire search', 1),
    array(14, 14, 'alg34', 'Demo binary search', 1),
    array(14, 15, 'alg35', 'Meten zoektijden', 1),
    array(14, 21, 'ml10', 'Cursus Z80 machinetaal voorbeeld 10', 1),
    array(14, 53, 'ijsfab', 'IJsfabriek', 1),
    array(14, 71, 'viper', 'Viper', 1),

    array(15, 9, 'icp4', 'Invoer Controle Programma 4', 1),
    array(15, 19, 'gelijk', 'Gelijk verdeeld test', 1),
    array(15, 20, 'gelbad', 'Gelijk verdeeld met slechte random generator', 1),
    array(15, 21, 'serie', 'Serie test (dobbelsteen)', 1),
    array(15, 22, 'serbad', 'Serie test met slechte random generator', 1),
    array(15, 23, 'dots', 'Grafische serie test', 1),
    array(15, 23, 'dotbad', 'Grafische serie test met slechte random generator', 1),
    array(15, 23, 'poker', 'Poker test', 1),
    array(15, 24, 'pkrbad', 'Poker test met slechte random generator', 1),
    array(15, 43, 'demoms', 'Demo muis', 1),
    array(15, 44, 'textms', 'Text muis', 1),
    array(15, 46, 'filems', 'File muis', 1),
    array(15, 48, 'drawms', 'Draw muis', 1),
    array(15, 0, 'blokms', 'Simpele grafiek', 1),
    array(15, 56, 'mcmprt', 'Afdrukprogramma bij MCM Data', 1),
    array(15, 63, 'drpasc', 'Driehoek van Pascal', 1),
    array(15, 0, 'newrnd', 'Goede random generator', 1),
    array(15, 0, 'mcarlo', 'Monte Carlo PI-schatting', 1),

    array(16, 0, 'kk16-3', 'beschrijving', 1),
    array(16, 0, 'kk16-6', 'beschrijving', 1),
    array(16, 0, 'macht2', 'beschrijving', 1),
    array(16, 0, 'msxbug', 'beschrijving', 1),
    array(16, 0, 'kk16-2', 'beschrijving', 1),
    array(16, 0, 'kk16-1', 'beschrijving', 1),
    array(16, 0, 'kk16-4', 'beschrijving', 1),
    array(16, 0, 'icp5', 'beschrijving', 1),
    array(16, 0, 'layout.pic', 'beschrijving', 1),
    array(16, 0, 'kk16-9', 'beschrijving', 1),
    array(16, 0, 'stack2', 'beschrijving', 1),
    array(16, 0, 'othell', 'beschrijving', 1),
    array(16, 0, 'wammes.pic', 'beschrijving', 1),
    array(16, 0, 'bcdmcm', 'beschrijving', 1),
    array(16, 0, 'drukker.pic', 'beschrijving', 1),
    array(16, 0, 'huis', 'beschrijving', 1),
    array(16, 0, 'planning.pic', 'beschrijving', 1),
    array(16, 0, 'ml13', 'beschrijving', 1),
    array(16, 0, 'kk16-5', 'beschrijving', 1),
    array(16, 0, 'carrou', 'beschrijving', 1),
    array(16, 0, 'ldpic', 'beschrijving', 1),
    array(16, 0, 'kk16-8', 'beschrijving', 1),
    array(16, 0, 'ml12', 'beschrijving', 1),
    array(16, 0, 'ml11', 'beschrijving', 1),
    array(16, 0, 'kk16-7', 'beschrijving', 1),
    array(16, 0, 'stack', 'beschrijving', 1),
    array(17, 0, 'ml16', 'beschrijving', 1),
    array(17, 0, 'hal', 'beschrijving', 1),
    array(17, 0, 'icp5', 'beschrijving', 1),
    array(17, 0, 'konami.pic', 'beschrijving', 1),
    array(17, 0, 'carr16', 'beschrijving', 1),
    array(17, 0, 'ldpic', 'beschrijving', 1),
    array(17, 0, 'ml15', 'beschrijving', 1),
    array(17, 0, 'dtp.pic', 'beschrijving', 1),
    array(17, 0, 'ml14', 'beschrijving', 1),
    array(17, 0, 'motto.pic', 'beschrijving', 1),
    array(18, 0, 'ml20', 'beschrijving', 1),
    array(18, 0, 'mcm2bs', 'beschrijving', 1),
    array(18, 0, 'ml18', 'beschrijving', 1),
    array(18, 0, 'ml19', 'beschrijving', 1),
    array(18, 0, 'icp5', 'beschrijving', 1),
    array(18, 0, 'koppie', 'beschrijving', 1),
    array(18, 0, 'disass', 'beschrijving', 1),
    array(18, 0, 'mcm2bm', 'beschrijving', 1),
    array(18, 0, 'ml17', 'beschrijving', 1),
    array(18, 0, 'mcm2b1', 'beschrijving', 1),
    array(19, 0, 'kochln', 'beschrijving', 1),
    array(19, 0, 'midnac', 'beschrijving', 1),
    array(19, 0, 'bm3', 'beschrijving', 1),
    array(19, 0, 'bm2', 'beschrijving', 1),
    array(19, 0, 'icp5', 'beschrijving', 1),
    array(19, 0, 'boer2', 'beschrijving', 1),
    array(19, 0, 'boer1', 'beschrijving', 1),
    array(19, 0, 'gosper', 'beschrijving', 1),
    array(19, 0, 'nuzijt', 'beschrijving', 1),
    array(19, 0, 'schaak', 'beschrijving', 1),
    array(19, 0, 'blast', 'beschrijving', 1),
    array(19, 0, 'stilna', 'beschrijving', 1),
    array(19, 0, 'draak', 'beschrijving', 1),
    array(19, 0, 'bm1', 'beschrijving', 1),
    array(19, 0, 'kochrc', 'beschrijving', 1),
    array(20, 0, 'sal88', 'beschrijving', 1),
    array(20, 0, 'fisc80', 'beschrijving', 1),
    array(20, 0, 'ml21', 'beschrijving', 1),
    array(20, 0, 'teken', 'beschrijving', 1),
    array(20, 0, 'icp5', 'beschrijving', 1),
    array(20, 0, 'ml22a', 'beschrijving', 1),
    array(20, 0, 'records.new', 'beschrijving', 1),
    array(20, 0, 'schaats', 'beschrijving', 1),
    array(20, 0, 'fisc40', 'beschrijving', 1),
    array(20, 0, 'tao', 'beschrijving', 1),
    array(20, 0, 'ml22', 'beschrijving', 1),
    array(21, 9, 'icp5', 'Invoer Controle programma 5', 1),
    array(21, 12, 'manga1', 'Manga 1', 1),
    array(21, 15, 'manga2', 'Manga 2', 1),
    array(21, 18, 'manga3', 'Manga 3', 1),
    array(21, 40, 'taoopl', 'Tao puzzle (oplossing)', 1),
    array(21, 46, 'dsort', 'Dsort', 1),
    array(21, 46, 'kalend', 'Kalender', 1),
    array(21, 54, 'laserb', 'Laserbikes', 1),
    array(22, 22, 'drwms2', 'DRWMS 2: Drawmuis', 2),
    array(22, 33, 'stackp', 'STACKP: Stackpointer', 1),
    array(22, 34, 'subst', 'SUBST', 1),
    array(22, 34, 'stkft1', 'STKFT: Stackfout 1', 1),
    array(22, 35, 'stkft2', 'STKFT2: Stackfout 2', 1),
    array(22, 36, 'balwrp', 'Balwerp', 1),
    array(22, 87, 'icp6', 'ICP/6: Invoer Controle Programma 6', 1),
    array(24, 0, 'icp6', 'beschrijving', 1),
    array(24, 0, 'pag', 'beschrijving', 1),
    array(24, 0, 'mcm2b2', 'beschrijving', 1),
    array(24, 0, 'lchkr2', 'beschrijving', 1),
    array(24, 0, 'lchkr1', 'beschrijving', 1),
    array(24, 0, 'crkls1', 'beschrijving', 1),
    array(24, 0, 'tol', 'beschrijving', 1),
    array(24, 0, 'loader', 'beschrijving', 1),
    array(24, 0, 'scrlll', 'beschrijving', 1),
    array(24, 0, 'dpsht', 'beschrijving', 1),
    array(24, 0, 'vrtgem', 'beschrijving', 1),
    array(24, 0, 'mcm2b4', 'beschrijving', 1),
    array(24, 0, 'mcm2b3', 'beschrijving', 1),
    array(24, 0, 'draai', 'beschrijving', 1),
    array(24, 0, 'crkls2', 'beschrijving', 1),
    array(24, 0, 'draw', 'beschrijving', 1),
    array(24, 0, 'mcm2bm', 'beschrijving', 1),
    array(25, 0, 'kopp2d', 'beschrijving', 1),
    array(25, 0, 'icp6', 'beschrijving', 1),
    array(25, 0, 'show2', 'beschrijving', 1),
    array(25, 0, 'mandel', 'beschrijving', 1),
    array(25, 0, 'teken', 'beschrijving', 1),
    array(25, 0, 'old', 'beschrijving', 1),
    array(25, 0, 'show8', 'beschrijving', 1),
    array(25, 0, 'datmak', 'beschrijving', 1),
    array(25, 0, 'sclrnd', 'beschrijving', 1),
    array(25, 0, 'enqt', 'beschrijving', 1),
    array(25, 0, 'kopp64', 'beschrijving', 1),
    array(25, 0, 'julia', 'beschrijving', 1),
    array(26, 0, 'clrspr', 'beschrijving', 1),
    array(26, 0, 'show8c', 'beschrijving', 1),
    array(26, 0, 'icp6', 'beschrijving', 1),
    array(26, 0, 'pkclr', 'beschrijving', 1),
    array(26, 0, 'savkrt', 'beschrijving', 1),
    array(26, 0, 'typmac', 'beschrijving', 1),
    array(26, 0, 'klaar', 'beschrijving', 1),
    array(26, 0, 'sclwlm', 'beschrijving', 1),
    array(26, 0, 'savpic', 'beschrijving', 1),
    array(26, 0, 'hondrd', 'beschrijving', 1),
    array(26, 0, 'lckrdt', 'beschrijving', 1),
    array(26, 0, 'show2c', 'beschrijving', 1),
    array(26, 0, 'fctuur', 'beschrijving', 1),
    array(26, 0, 'tvdp24', 'beschrijving', 1),
    array(26, 0, 'lckrsb', 'beschrijving', 1),
    array(26, 0, 'lckr26', 'beschrijving', 1),
    array(26, 0, 'lckrlg', 'beschrijving', 1),
    array(27, 0, 'icp6', 'beschrijving', 1),
    array(27, 0, 'keyin', 'beschrijving', 1),
    array(27, 0, 'tutor1', 'beschrijving', 1),
    array(27, 0, 'vamp2.pic', 'beschrijving', 1),
    array(27, 0, 'kerst.pic', 'beschrijving', 1),
    array(27, 0, 'crsfn', 'beschrijving', 1),
    array(27, 0, 'follow', 'beschrijving', 1),
    array(27, 0, 'tutor2', 'beschrijving', 1),
    array(27, 0, 'ranseq', 'beschrijving', 1),
    array(27, 0, 'tank2.bas', 'beschrijving', 1),
    array(27, 0, 'intro.pic', 'beschrijving', 1),
    array(27, 0, 'beep2', 'beschrijving', 1),
    array(27, 0, 'kerst', 'beschrijving', 1),
    array(27, 0, 'beep1', 'beschrijving', 1),
    array(28, 0, 'fsc89l', 'beschrijving', 1),
    array(28, 0, 'icp6', 'beschrijving', 1),
    array(28, 0, 'loon89', 'beschrijving', 1),
    array(28, 0, 'fsc89h', 'beschrijving', 1),
    array(28, 0, 'kk28-4', 'beschrijving', 1),
    array(28, 0, 'kk28-8', 'beschrijving', 1),
    array(28, 0, 'mcm2o4', 'beschrijving', 1),
    array(28, 0, 'kk28-6', 'beschrijving', 1),
    array(28, 0, 'kk28-5', 'beschrijving', 1),
    array(28, 0, 'mcm2o3', 'beschrijving', 1),
    array(28, 0, 'kprelf', 'beschrijving', 1),
    array(28, 0, 'sal89', 'beschrijving', 1),
    array(28, 0, 'kprele', 'beschrijving', 1),
    array(28, 0, 'kk28-2', 'beschrijving', 1),
    array(28, 0, 'kk28-7', 'beschrijving', 1),
    array(28, 0, 'gefeli', 'beschrijving', 1),
    array(28, 0, 'fdate', 'beschrijving', 1),
    array(28, 0, 'kpreld', 'beschrijving', 1),
    array(28, 0, 'mcm2o2', 'beschrijving', 1),
    array(28, 0, 'mcm2o1', 'beschrijving', 1),
    array(28, 0, 'kk28-3', 'beschrijving', 1),
    array(28, 0, 'cstutr', 'beschrijving', 1),
    array(29, 0, 'icp6', 'beschrijving', 1),
    array(29, 0, 'fsc89h', 'beschrijving', 1),
    array(29, 0, 'ftime', 'beschrijving', 1),
    array(29, 0, 'vertoon', 'beschrijving', 1),
    array(29, 0, 'konami2.pic', 'beschrijving', 1),
    array(29, 0, 'rmdbin', 'beschrijving', 1),
    array(29, 0, 'kilspb', 'beschrijving', 1),
    array(29, 0, 'pasen', 'beschrijving', 1),
    array(29, 0, 'konami1.pic', 'beschrijving', 1),
    array(29, 0, 'rdinst', 'beschrijving', 1),
    array(29, 0, 'ramdsk', 'beschrijving', 1),
    array(29, 0, 'ftime.com', 'beschrijving', 1),
    array(29, 0, 'kilspc', 'beschrijving', 1),
    array(29, 0, 'vuurwerk.pic', 'beschrijving', 1),
    array(29, 0, 'hrstl', 'beschrijving', 1),
    array(29, 0, 'kaars.pic', 'beschrijving', 1),
    array(29, 0, 'fisc89', 'beschrijving', 1),
    array(30, 0, 'icp6', 'beschrijving', 1),
    array(30, 0, 'schn2', 'beschrijving', 1),
    array(30, 0, 'intlac', 'beschrijving', 1),
    array(30, 0, 'haard3', 'beschrijving', 1),
    array(30, 0, 'vertoon', 'beschrijving', 1),
    array(30, 0, 'dmsxmag.pic', 'beschrijving', 1),
    array(30, 0, 'truck.pic', 'beschrijving', 1),
    array(30, 0, 'haard1', 'beschrijving', 1),
    array(30, 0, 'haard4', 'beschrijving', 1),
    array(30, 0, 'blokjs', 'beschrijving', 1),
    array(30, 0, 'schn1', 'beschrijving', 1),
    array(30, 0, 'spritmix.pic', 'beschrijving', 1),
    array(30, 0, 'lissaj', 'beschrijving', 1),
    array(30, 0, 'legenda.pic', 'beschrijving', 1),
    array(30, 0, 'sterrn', 'beschrijving', 1),
    array(30, 0, 'haard2', 'beschrijving', 1),
    array(30, 0, 'schuif', 'beschrijving', 1),
    array(31, 0, 'forest.pic', 'beschrijving', 1),
    array(31, 0, 'icp6', 'beschrijving', 1),
    array(31, 0, 'tank.pic', 'beschrijving', 1),
    array(31, 0, 'more', 'beschrijving', 1),
    array(31, 0, 'vertoon', 'beschrijving', 1),
    array(31, 0, 'more.com', 'beschrijving', 1),
    array(31, 0, 'diskvw.com', 'beschrijving', 1),
    array(31, 0, 'morass', 'beschrijving', 1),
    array(31, 0, 'filshw', 'beschrijving', 1),
    array(31, 0, 'system', 'beschrijving', 1),
    array(31, 0, 'filedt', 'beschrijving', 1),
    array(31, 0, 'columbia.pic', 'beschrijving', 1),
    array(31, 0, 'thecreep.pic', 'beschrijving', 1),
    array(31, 0, 'filfnd', 'beschrijving', 1),
    array(31, 0, 'schcor', 'beschrijving', 1),
    array(31, 0, 'diskvw', 'beschrijving', 1),
    array(31, 0, 'kinval', 'beschrijving', 1),
    array(31, 0, 'dvinst', 'beschrijving', 1),
    array(32, 0, 'icp6', 'beschrijving', 1),
    array(32, 0, 'blkjs3', 'beschrijving', 1),
    array(32, 0, 'vertoon', 'beschrijving', 1),
    array(32, 0, 'transfer.com', 'beschrijving', 1),
    array(32, 0, 'blkjs2', 'beschrijving', 1),
    array(32, 0, 'trnsfr', 'beschrijving', 1),
    array(32, 0, 'leski.pic', 'beschrijving', 1),
    array(32, 0, 'rolls.pic', 'beschrijving', 1),
    array(32, 0, 'blkjs4', 'beschrijving', 1),
    array(32, 0, 'gordyn', 'beschrijving', 1),
    array(32, 0, 'flappy2.pic', 'beschrijving', 1),
    array(32, 0, 'uil.pic', 'beschrijving', 1),
    array(32, 0, 'blkjs1', 'beschrijving', 1),
    array(33, 0, 'salamndr.pic', 'beschrijving', 1),
    array(33, 0, 'icp6', 'beschrijving', 1),
    array(33, 0, 'scc2', 'beschrijving', 1),
    array(33, 0, 'sccvb', 'beschrijving', 1),
    array(33, 0, 'bergen.pic', 'beschrijving', 1),
    array(33, 0, 'vertoon', 'beschrijving', 1),
    array(33, 0, 'iotje.bas', 'beschrijving', 1),
    array(33, 0, '4096', 'beschrijving', 1),
    array(33, 0, 'asctab', 'beschrijving', 1),
    array(33, 0, 'konami.bas', 'beschrijving', 1),
    array(33, 0, 'basicscc.001', 'beschrijving', 1),
    array(33, 0, 'basicscc.002', 'beschrijving', 1),
    array(33, 0, 'karst1', 'beschrijving', 1),
    array(33, 0, 'basicscc.003', 'beschrijving', 1),
    array(33, 0, 'space.pic', 'beschrijving', 1),
    array(33, 0, 'msx1sc', 'beschrijving', 1),
    array(33, 0, 'karst2', 'beschrijving', 1),
    array(33, 0, 'haard6', 'beschrijving', 1),
    array(33, 0, 'tydmnu', 'beschrijving', 1),
    array(33, 0, 'basicscc.004', 'beschrijving', 1),
    array(33, 0, 'motor.scc', 'beschrijving', 1),
    array(33, 0, 'plms1.pic', 'beschrijving', 1),
    array(33, 0, 'plms2.pic', 'beschrijving', 1),
    array(33, 0, 'ascasm', 'beschrijving', 1),
    array(33, 0, 'plms.bas', 'beschrijving', 1),
    array(33, 0, 'scc1', 'beschrijving', 1),
    array(33, 0, 'haard5', 'beschrijving', 1),
    array(33, 0, 'intlc2', 'beschrijving', 1),
    array(34, 0, 'icp6', 'beschrijving', 1),
    array(34, 0, 'icp7b', 'beschrijving', 1),
    array(34, 0, 'klrsns', 'beschrijving', 1),
    array(34, 0, 'sntkst', 'beschrijving', 1),
    array(34, 0, 'crvir69.pic', 'beschrijving', 1),
    array(34, 0, 'show33', 'beschrijving', 1),
    array(34, 0, 'fmpak', 'beschrijving', 1),
    array(34, 0, 'm2b4ex', 'beschrijving', 1),
    array(34, 0, 'tydmnu', 'beschrijving', 1),
    array(34, 0, 'crvir21.pic', 'beschrijving', 1),
    array(34, 0, 'crlan100.pic', 'beschrijving', 1),
    array(34, 0, 'klrsn2', 'beschrijving', 1),
    array(34, 0, 'rymele', 'beschrijving', 1),
    array(34, 0, 'icp7', 'beschrijving', 1),
    array(34, 0, 'smile2', 'beschrijving', 1),
    array(34, 0, 'jungle', 'beschrijving', 1),
    array(35, 0, 'icp6', 'beschrijving', 1),
    array(35, 0, 'lixenbg2.pic', 'beschrijving', 1),
    array(35, 0, 'epson.doc', 'beschrijving', 1),
    array(35, 0, 'haard9', 'beschrijving', 1),
    array(35, 0, 'haard8', 'beschrijving', 1),
    array(35, 0, 'hard9b', 'beschrijving', 1),
    array(35, 0, 'seppat', 'beschrijving', 1),
    array(35, 0, 'id', 'beschrijving', 1),
    array(35, 0, 'easpatch.com', 'beschrijving', 1),
    array(35, 0, 'romein.pic', 'beschrijving', 1),
    array(35, 0, 'jingbl', 'beschrijving', 1),
    array(35, 0, 'dynasta7.pic', 'beschrijving', 1),
    array(35, 0, 'dynasta5.pic', 'beschrijving', 1),
    array(35, 0, 'show34', 'beschrijving', 1),
    array(35, 0, 'haard7', 'beschrijving', 1),
    array(35, 0, 'marybo', 'beschrijving', 1),
    array(35, 0, 'vuurwk', 'beschrijving', 1),
    array(35, 0, 'life', 'beschrijving', 1),
    array(35, 0, 'patch', 'beschrijving', 1),
    array(35, 0, 'hrkang', 'beschrijving', 1),
    array(35, 0, 'kaars', 'beschrijving', 1),
    array(35, 0, 'wewish', 'beschrijving', 1),
    array(35, 0, 'hard10', 'beschrijving', 1),
    array(35, 0, 'kerst', 'beschrijving', 1),
    array(35, 0, 'balkensp.pic', 'beschrijving', 1),
    array(36, 0, 'icp6', 'beschrijving', 1),
    array(36, 0, 'icp7b', 'beschrijving', 1),
    array(36, 0, 'carrier', 'beschrijving', 1),
    array(36, 0, 'alpine', 'beschrijving', 1),
    array(36, 0, 'rgnbg', 'beschrijving', 1),
    array(36, 0, 'duif.pic', 'beschrijving', 1),
    array(36, 0, 'hola', 'beschrijving', 1),
    array(36, 0, 'wu_shu.pic', 'beschrijving', 1),
    array(36, 0, 'carrier.bin', 'beschrijving', 1),
    array(36, 0, 'pasmog', 'beschrijving', 1),
    array(36, 0, 'wandel', 'beschrijving', 1),
    array(36, 0, 'supprt', 'beschrijving', 1),
    array(36, 0, 'show35', 'beschrijving', 1),
    array(36, 0, 'brdr1', 'beschrijving', 1),
    array(36, 0, 'brdr2', 'beschrijving', 1),
    array(36, 0, 'icp7', 'beschrijving', 1),
    array(36, 0, 'mask3.pic', 'beschrijving', 1),
    array(36, 0, 'sal90', 'beschrijving', 1),
    array(37, 0, 'icp6', 'beschrijving', 1),
    array(37, 0, 'scrnl5', 'beschrijving', 1),
    array(37, 0, 'icp7b', 'beschrijving', 1),
    array(37, 0, 'fiscus40.90', 'beschrijving', 1),
    array(37, 0, 'fiscus.90', 'beschrijving', 1),
    array(37, 0, 'ridder.pic', 'beschrijving', 1),
    array(37, 0, 'show36', 'beschrijving', 1),
    array(37, 0, 'axelf', 'beschrijving', 1),
    array(37, 0, 'intlc3', 'beschrijving', 1),
    array(37, 0, 'padkey', 'beschrijving', 1),
    array(37, 0, 'scrnl1', 'beschrijving', 1),
    array(37, 0, 'int.pic', 'beschrijving', 1),
    array(37, 0, 'menu', 'beschrijving', 1),
    array(37, 0, 'fstart', 'beschrijving', 1),
    array(37, 0, 'tstprt', 'beschrijving', 1),
    array(37, 0, 'pdkey2', 'beschrijving', 1),
    array(37, 0, 'intsc8', 'beschrijving', 1),
    array(37, 0, 'beeper', 'beschrijving', 1),
    array(37, 0, 'simpel', 'beschrijving', 1),
    array(37, 0, 'bergland.pic', 'beschrijving', 1),
    array(37, 0, 'effici', 'beschrijving', 1),
    array(37, 0, 'scrnl2', 'beschrijving', 1),
    array(37, 0, 'zoomlens.pic', 'beschrijving', 1),
    array(37, 0, 'seppt2', 'beschrijving', 1),
    array(37, 0, 'icp7', 'beschrijving', 1),
    array(37, 0, 'scrnl3', 'beschrijving', 1),
    array(37, 0, 'breedt', 'beschrijving', 1),
    array(37, 0, 'scrnl4', 'beschrijving', 1),
    array(38, 0, 'strofz', 'beschrijving', 1),
    array(38, 0, 'scrsav', 'beschrijving', 1),
    array(38, 0, 'icp6', 'beschrijving', 1),
    array(38, 0, 'icp7b', 'beschrijving', 1),
    array(38, 0, 'gullit.pic', 'beschrijving', 1),
    array(38, 0, 'drdat', 'beschrijving', 1),
    array(38, 0, 'mcbcmcm2.ldr', 'beschrijving', 1),
    array(38, 0, 'lc10dp', 'beschrijving', 1),
    array(38, 0, 'autoexec.bat', 'beschrijving', 1),
    array(38, 0, 'toekomst.pic', 'beschrijving', 1),
    array(38, 0, 'scrpch', 'beschrijving', 1),
    array(38, 0, 'vb-lst', 'beschrijving', 1),
    array(38, 0, 'corvette.pic', 'beschrijving', 1),
    array(38, 0, 'mcbcmcm2.bas', 'beschrijving', 1),
    array(38, 0, 'cujomu', 'beschrijving', 1),
    array(38, 0, 'cmdemo', 'beschrijving', 1),
    array(38, 0, 'krkklk', 'beschrijving', 1),
    array(38, 0, 'show37', 'beschrijving', 1),
    array(38, 0, 'brdclr', 'beschrijving', 1),
    array(38, 0, 'list', 'beschrijving', 1),
    array(38, 0, 'zasbas', 'beschrijving', 1),
    array(38, 0, 'girl.pic', 'beschrijving', 1),
    array(38, 0, 'linprt', 'beschrijving', 1),
    array(38, 0, 'tobuf', 'beschrijving', 1),
    array(38, 0, 'vb-bas', 'beschrijving', 1),
    array(38, 0, 'dvpat1', 'beschrijving', 1),
    array(38, 0, 'potlod', 'beschrijving', 1),
    array(38, 0, 'tekst', 'beschrijving', 1),
    array(38, 0, 'abhstr', 'beschrijving', 1),
    array(38, 0, 'token', 'beschrijving', 1),
    array(38, 0, 'linlen', 'beschrijving', 1),
    array(38, 0, 'mcbcmcm1.bas', 'beschrijving', 1),
    array(38, 0, 'vb-asm', 'beschrijving', 1),
    array(38, 0, 'tennis.pic', 'beschrijving', 1),
    array(38, 0, 'icp7', 'beschrijving', 1),
    array(38, 0, 'mcbcmcm1.ldr', 'beschrijving', 1),
    array(38, 0, 'despat', 'beschrijving', 1),
    array(38, 0, 'storin', 'beschrijving', 1),
    array(39, 0, 'icp7b', 'beschrijving', 1),
    array(39, 0, 'turmite.pic', 'beschrijving', 1),
    array(39, 0, 'cycle_6.pic', 'beschrijving', 1),
    array(39, 0, 'zadel', 'beschrijving', 1),
    array(39, 0, 'show38', 'beschrijving', 1),
    array(39, 0, 'vdp1', 'beschrijving', 1),
    array(39, 0, 'hande_01.pic', 'beschrijving', 1),
    array(39, 0, 'hdskl1', 'beschrijving', 1),
    array(39, 0, 'ataripr2.bin', 'beschrijving', 1),
    array(39, 0, 'ataripr1.bin', 'beschrijving', 1),
    array(39, 0, 'vdp5', 'beschrijving', 1),
    array(39, 0, 'ataripr1.asm', 'beschrijving', 1),
    array(39, 0, 'atari.asm', 'beschrijving', 1),
    array(39, 0, 'atari', 'beschrijving', 1),
    array(39, 0, 'fprint.com', 'beschrijving', 1),
    array(39, 0, 'vdp2', 'beschrijving', 1),
    array(39, 0, 'atari.bas', 'beschrijving', 1),
    array(39, 0, 'atari.txt', 'beschrijving', 1),
    array(39, 0, 'fprint', 'beschrijving', 1),
    array(39, 0, 'atari.bin', 'beschrijving', 1),
    array(39, 0, 'chared', 'beschrijving', 1),
    array(39, 0, 'blokkn', 'beschrijving', 1),
    array(39, 0, 'komputer.sc7', 'beschrijving', 1),
    array(39, 0, 'vdp3', 'beschrijving', 1),
    array(39, 0, 'tikken', 'beschrijving', 1),
    array(39, 0, 'abstrakt.sc7', 'beschrijving', 1),
    array(39, 0, 'mcmmcm', 'beschrijving', 1),
    array(39, 0, 'ataripr2.asm', 'beschrijving', 1),
    array(39, 0, 'spinnen1.pic', 'beschrijving', 1),
    array(39, 0, 'icp7', 'beschrijving', 1),
    array(39, 0, 'vdp4', 'beschrijving', 1),
    array(40, 0, 'rubklk', 'beschrijving', 1),
    array(40, 0, 'bk.txt', 'beschrijving', 1),
    array(40, 0, 'adelaar.pic', 'beschrijving', 1),
    array(40, 0, 'swap', 'beschrijving', 1),
    array(40, 0, 'swap.com', 'beschrijving', 1),
    array(40, 0, 'swap2', 'beschrijving', 1),
    array(40, 0, 'mtype.com', 'beschrijving', 1),
    array(40, 0, 'space.pic', 'beschrijving', 1),
    array(40, 0, 'mtype.gen', 'beschrijving', 1),
    array(40, 0, 'memman.txt', 'beschrijving', 1),
    array(40, 0, 'autotx', 'beschrijving', 1),
    array(40, 0, 'autoexe1', 'beschrijving', 1),
    array(40, 0, 'autoexe2', 'beschrijving', 1),
    array(40, 0, 'autoexec.cop', 'beschrijving', 1),
    array(40, 0, 'memman.com', 'beschrijving', 1),
    array(40, 0, 'show39', 'beschrijving', 1),
    array(40, 0, 'cfgmman.bas', 'beschrijving', 1),
    array(40, 0, 'memman.bin', 'beschrijving', 1),
    array(40, 0, 'tafel.asm', 'beschrijving', 1),
    array(40, 0, 'compbird.pic', 'beschrijving', 1),
    array(40, 0, 'queen.sc7', 'beschrijving', 1),
    array(40, 0, 'bk.com', 'beschrijving', 1),
    array(40, 0, 'icp7', 'beschrijving', 1),
    array(40, 0, 'icp7.bin', 'beschrijving', 1),
    array(41, 0, 'pbna24', 'beschrijving', 1),
    array(41, 0, 'pbna20', 'beschrijving', 1),
    array(41, 0, 'pbna16', 'beschrijving', 1),
    array(41, 0, 'pbna25', 'beschrijving', 1),
    array(41, 0, 'swaptypl', 'beschrijving', 1),
    array(41, 0, 'diashw', 'beschrijving', 1),
    array(41, 0, 'datab', 'beschrijving', 1),
    array(41, 0, 'pbna03', 'beschrijving', 1),
    array(41, 0, 'pbna14', 'beschrijving', 1),
    array(41, 0, 'permut', 'beschrijving', 1),
    array(41, 0, 'pbna12', 'beschrijving', 1),
    array(41, 0, 'pbna06', 'beschrijving', 1),
    array(41, 0, '10fkey', 'beschrijving', 1),
    array(41, 0, 'pbna17', 'beschrijving', 1),
    array(41, 0, 'pbna02', 'beschrijving', 1),
    array(41, 0, 'pbna28', 'beschrijving', 1),
    array(41, 0, 'pbna04', 'beschrijving', 1),
    array(41, 0, 'pbna01', 'beschrijving', 1),
    array(41, 0, 'pbna05', 'beschrijving', 1),
    array(41, 0, 'pbna07', 'beschrijving', 1),
    array(41, 0, 'bootx', 'beschrijving', 1),
    array(41, 0, 'pbna27', 'beschrijving', 1),
    array(41, 0, 'pbna21', 'beschrijving', 1),
    array(41, 0, 'buschauf.pic', 'beschrijving', 1),
    array(41, 0, 'pbna26', 'beschrijving', 1),
    array(41, 0, 'swaptype', 'beschrijving', 1),
    array(41, 0, 'autotx', 'beschrijving', 1),
    array(41, 0, 'eiffel3.pic', 'beschrijving', 1),
    array(41, 0, 'autoexe1', 'beschrijving', 1),
    array(41, 0, 'autoexe2', 'beschrijving', 1),
    array(41, 0, 'pbna08', 'beschrijving', 1),
    array(41, 0, 'diver', 'beschrijving', 1),
    array(41, 0, 'fractal9.pic', 'beschrijving', 1),
    array(41, 0, 'autoexec.cop', 'beschrijving', 1),
    array(41, 0, 'busbestu.pic', 'beschrijving', 1),
    array(41, 0, 'pbna11', 'beschrijving', 1),
    array(41, 0, 'pbna22', 'beschrijving', 1),
    array(41, 0, 'pbna09', 'beschrijving', 1),
    array(41, 0, 'pbna18', 'beschrijving', 1),
    array(41, 0, 'pbna13', 'beschrijving', 1),
    array(41, 0, 'pbna10', 'beschrijving', 1),
    array(41, 0, 'koeien.pic', 'beschrijving', 1),
    array(41, 0, 'pbna15', 'beschrijving', 1),
    array(41, 0, 'pbna23', 'beschrijving', 1),
    array(41, 0, 'icp7', 'beschrijving', 1),
    array(41, 0, 'icp7.bin', 'beschrijving', 1),
    array(41, 0, 'pbna19', 'beschrijving', 1),
    array(42, 0, 'diashw', 'beschrijving', 1),
    array(42, 0, 'frscr', 'beschrijving', 1),
    array(42, 0, 'vdpasm', 'beschrijving', 1),
    array(42, 0, 'slayer.scr', 'beschrijving', 1),
    array(42, 0, 'timer', 'beschrijving', 1),
    array(42, 0, 'icp7.asc', 'beschrijving', 1),
    array(42, 0, 'flstot.bin', 'beschrijving', 1),
    array(42, 0, 'fourklr.scr', 'beschrijving', 1),
    array(42, 0, 'motor.fin', 'beschrijving', 1),
    array(42, 0, 'queensr.scr', 'beschrijving', 1),
    array(42, 0, 'sftgrp', 'beschrijving', 1),
    array(42, 0, 'heineken.scr', 'beschrijving', 1),
    array(42, 0, 'autotx', 'beschrijving', 1),
    array(42, 0, 'tschai5.pic', 'beschrijving', 1),
    array(42, 0, 'death.scr', 'beschrijving', 1),
    array(42, 0, 'casfil', 'beschrijving', 1),
    array(42, 0, 'paling.gec', 'beschrijving', 1),
    array(42, 0, 'autoexe1', 'beschrijving', 1),
    array(42, 0, 'autoexe2', 'beschrijving', 1),
    array(42, 0, 'four', 'beschrijving', 1),
    array(42, 0, 'vdp', 'beschrijving', 1),
    array(42, 0, 'artsc2', 'beschrijving', 1),
    array(42, 0, 'autoexec.cop', 'beschrijving', 1),
    array(42, 0, 'ml3l2.a42', 'beschrijving', 1),
    array(42, 0, 'baskey', 'beschrijving', 1),
    array(42, 0, 'casvb.asc', 'beschrijving', 1),
    array(42, 0, 'motor.opb', 'beschrijving', 1),
    array(42, 0, 'ml3l1.a42', 'beschrijving', 1),
    array(42, 0, 'flstot', 'beschrijving', 1),
    array(42, 0, 'matrix', 'beschrijving', 1),
    array(42, 0, 'tschai8.pic', 'beschrijving', 1),
    array(42, 0, 'maiden.scr', 'beschrijving', 1),
    array(43, 0, 'makdat', 'beschrijving', 1),
    array(43, 0, 'breakout.pic', 'beschrijving', 1),
    array(43, 0, 'diashw', 'beschrijving', 1),
    array(43, 0, 'witch.sc8', 'beschrijving', 1),
    array(43, 0, 'movmak', 'beschrijving', 1),
    array(43, 0, 'ninja1.pic', 'beschrijving', 1),
    array(43, 0, 'yswinter.sc8', 'beschrijving', 1),
    array(43, 0, 'piggy2.mov', 'beschrijving', 1),
    array(43, 0, 'printat', 'beschrijving', 1),
    array(43, 0, 'kunst2.pic', 'beschrijving', 1),
    array(43, 0, 'autotx', 'beschrijving', 1),
    array(43, 0, 'autoexe1', 'beschrijving', 1),
    array(43, 0, 'autoexe2', 'beschrijving', 1),
    array(43, 0, 'knippr', 'beschrijving', 1),
    array(43, 0, 'casfil43.asc', 'beschrijving', 1),
    array(43, 0, 'autoexec.cop', 'beschrijving', 1),
    array(43, 0, 'cirgam', 'beschrijving', 1),
    array(43, 0, 'krul', 'beschrijving', 1),
    array(43, 0, 'mcm.mov', 'beschrijving', 1),
    array(43, 0, 'agame', 'beschrijving', 1),
    array(43, 0, 'diskan', 'beschrijving', 1),
    array(43, 0, 'icp7', 'beschrijving', 1),
    array(43, 0, 'dried', 'beschrijving', 1),
    array(43, 0, 'icp7.bin', 'beschrijving', 1),
    array(43, 0, 'gemeen', 'beschrijving', 1),
    array(44, 0, 'diashw', 'beschrijving', 1),
    array(44, 0, '(herfst).pic', 'beschrijving', 1),
    array(44, 0, 'hv&d.bin', 'beschrijving', 1),
    array(44, 0, 'funed', 'beschrijving', 1),
    array(44, 0, 'hoed.mov', 'beschrijving', 1),
    array(44, 0, 'paddestl.pic', 'beschrijving', 1),
    array(44, 0, 'autotx', 'beschrijving', 1),
    array(44, 0, 'scroll', 'beschrijving', 1),
    array(44, 0, 'autoexe1', 'beschrijving', 1),
    array(44, 0, 'hv&dbin', 'beschrijving', 1),
    array(44, 0, 'autoexe2', 'beschrijving', 1),
    array(44, 0, 'muur.pic', 'beschrijving', 1),
    array(44, 0, 'autoexec.cop', 'beschrijving', 1),
    array(44, 0, 'scroll.bin', 'beschrijving', 1),
    array(44, 0, 'anidat', 'beschrijving', 1),
    array(44, 0, 'animat.dat', 'beschrijving', 1),
    array(44, 0, 'hv&d', 'beschrijving', 1),
    array(44, 0, 'scrollbi', 'beschrijving', 1),
    array(44, 0, 'mathpk', 'beschrijving', 1),
    array(44, 0, 'sal91', 'beschrijving', 1),
    array(44, 0, 'smidse.pic', 'beschrijving', 1),
    array(44, 0, 'icp7', 'beschrijving', 1),
    array(44, 0, 'pijl.mov', 'beschrijving', 1),
    array(44, 0, 'icp7.bin', 'beschrijving', 1),
    array(44, 0, 'dactst', 'beschrijving', 1),
    array(44, 0, 'animat', 'beschrijving', 1),
    array(45, 0, 'bk.ted', 'beschrijving', 1),
    array(45, 0, 'mm2intro.ted', 'beschrijving', 1),
    array(45, 0, 'tk.com', 'beschrijving', 1),
    array(45, 0, 'bk.txt', 'beschrijving', 1),
    array(45, 0, 'react1', 'beschrijving', 1),
    array(45, 0, 'scr3vb4', 'beschrijving', 1),
    array(45, 0, 'moza8', 'beschrijving', 1),
    array(45, 0, 'caps.tsr', 'beschrijving', 1),
    array(45, 0, 'ehbo2', 'beschrijving', 1),
    array(45, 0, 'movpatch', 'beschrijving', 1),
    array(45, 0, 'memman2.arc', 'beschrijving', 1),
    array(45, 0, 'mdlbas', 'beschrijving', 1),
    array(45, 0, 'klokje', 'beschrijving', 1),
    array(45, 0, 'chgcpu', 'beschrijving', 1),
    array(45, 0, 'mtype.com', 'beschrijving', 1),
    array(45, 0, 'scr3vb1', 'beschrijving', 1),
    array(45, 0, 'mtype.gen', 'beschrijving', 1),
    array(45, 0, 'tl.com', 'beschrijving', 1),
    array(45, 0, 'autotx', 'beschrijving', 1),
    array(45, 0, 'scr3vb7', 'beschrijving', 1),
    array(45, 0, 'color.tsr', 'beschrijving', 1),
    array(45, 0, 'scr3vb5', 'beschrijving', 1),
    array(45, 0, 'react2', 'beschrijving', 1),
    array(45, 0, 'rond3', 'beschrijving', 1),
    array(45, 0, 'autoexe1', 'beschrijving', 1),
    array(45, 0, 'rond2', 'beschrijving', 1),
    array(45, 0, 'autoexe2', 'beschrijving', 1),
    array(45, 0, 'scr3vb6', 'beschrijving', 1),
    array(45, 0, 'mltabs.asc', 'beschrijving', 1),
    array(45, 0, 'autoexec.cop', 'beschrijving', 1),
    array(45, 0, 'memman.com', 'beschrijving', 1),
    array(45, 0, 'moza8bis', 'beschrijving', 1),
    array(45, 0, 'chgcpu.com', 'beschrijving', 1),
    array(45, 0, 'memman.bin', 'beschrijving', 1),
    array(45, 0, 'cfgmman.com', 'beschrijving', 1),
    array(45, 0, 'diapatch', 'beschrijving', 1),
    array(45, 0, 'scr3vb3', 'beschrijving', 1),
    array(45, 0, 'balk', 'beschrijving', 1),
    array(45, 0, 'smileb', 'beschrijving', 1),
    array(45, 0, 'mm2specs.txt', 'beschrijving', 1),
    array(45, 0, 'mm2specs.ted', 'beschrijving', 1),
    array(45, 0, 'tikker', 'beschrijving', 1),
    array(45, 0, 'scr3vb2', 'beschrijving', 1),
    array(45, 0, 'bk.com', 'beschrijving', 1),
    array(45, 0, 'icp7', 'beschrijving', 1),
    array(45, 0, 'mm2intro.txt', 'beschrijving', 1),
    array(45, 0, 'mdlpas.asc', 'beschrijving', 1),
    array(45, 0, 'ehbo1', 'beschrijving', 1),
    array(45, 0, 'rond1', 'beschrijving', 1),
    array(45, 0, 'icp7.bin', 'beschrijving', 1),
    array(45, 0, 'smile', 'beschrijving', 1),
    array(45, 0, 'tv.com', 'beschrijving', 1),
    array(45, 0, 'moza3', 'beschrijving', 1),
    array(46, 0, 'zas5l2.asm', 'beschrijving', 1),
    array(46, 0, 'cyclus', 'beschrijving', 1),
    array(46, 0, 'kantk1', 'beschrijving', 1),
    array(46, 0, 'diashw', 'beschrijving', 1),
    array(46, 0, 'barbie', 'beschrijving', 1),
    array(46, 0, 'dr4kt4', 'beschrijving', 1),
    array(46, 0, 'pbl1', 'beschrijving', 1),
    array(46, 0, 'zas5l1.asm', 'beschrijving', 1),
    array(46, 0, 'tk.com', 'beschrijving', 1),
    array(46, 0, 'exprif', 'beschrijving', 1),
    array(46, 0, 'ehbo45l2.asc', 'beschrijving', 1),
    array(46, 0, 'caps.tsr', 'beschrijving', 1),
    array(46, 0, 'zas5l4.asm', 'beschrijving', 1),
    array(46, 0, '8245b', 'beschrijving', 1),
    array(46, 0, 'knppr2as.asc', 'beschrijving', 1),
    array(46, 0, 'knppr2', 'beschrijving', 1),
    array(46, 0, 'mm22spec.txt', 'beschrijving', 1),
    array(46, 0, 'print.com', 'beschrijving', 1),
    array(46, 0, 'square', 'beschrijving', 1),
    array(46, 0, 'tl.com', 'beschrijving', 1),
    array(46, 0, 'autotx', 'beschrijving', 1),
    array(46, 0, 'kantk2', 'beschrijving', 1),
    array(46, 0, 'dr4kt1', 'beschrijving', 1),
    array(46, 0, 'vlindr', 'beschrijving', 1),
    array(46, 0, 'autoexe1', 'beschrijving', 1),
    array(46, 0, 'autoexe2', 'beschrijving', 1),
    array(46, 0, 'newstar.pic', 'beschrijving', 1),
    array(46, 0, 'pb.tsr', 'beschrijving', 1),
    array(46, 0, 'autoexec.cop', 'beschrijving', 1),
    array(46, 0, 'memman.com', 'beschrijving', 1),
    array(46, 0, 'museum.pic', 'beschrijving', 1),
    array(46, 0, 'memman.bin', 'beschrijving', 1),
    array(46, 0, 'fregol2.ge7', 'beschrijving', 1),
    array(46, 0, 'letben', 'beschrijving', 1),
    array(46, 0, 'dr4kt3', 'beschrijving', 1),
    array(46, 0, 'cfgmman.com', 'beschrijving', 1),
    array(46, 0, 'pbl2', 'beschrijving', 1),
    array(46, 0, 'zas5l3.asm', 'beschrijving', 1),
    array(46, 0, '8245a', 'beschrijving', 1),
    array(46, 0, 'gloei', 'beschrijving', 1),
    array(46, 0, 'mcmnum', 'beschrijving', 1),
    array(46, 0, 'lanta.pic', 'beschrijving', 1),
    array(46, 0, 'icp7', 'beschrijving', 1),
    array(46, 0, 'mm2intro.txt', 'beschrijving', 1),
    array(46, 0, 'dr4kt2', 'beschrijving', 1),
    array(46, 0, 'icp7.bin', 'beschrijving', 1),
    array(46, 0, 'tv.com', 'beschrijving', 1),
    array(47, 0, 'hspel1.s08', 'beschrijving', 1),
    array(47, 0, 'soundl4.bas', 'beschrijving', 1),
    array(47, 0, 'soundl2.bas', 'beschrijving', 1),
    array(47, 0, 'cycloop.s12', 'beschrijving', 1),
    array(47, 0, 'bardemo.bas', 'beschrijving', 1),
    array(47, 0, 'tk.com', 'beschrijving', 1),
    array(47, 0, 'scr12-11.bas', 'beschrijving', 1),
    array(47, 0, 'soundl6.bas', 'beschrijving', 1),
    array(47, 0, 'mm23spec.txt', 'beschrijving', 1),
    array(47, 0, 'soundl1.bas', 'beschrijving', 1),
    array(47, 0, 'roteer.bas', 'beschrijving', 1),
    array(47, 0, 'caps.tsr', 'beschrijving', 1),
    array(47, 0, 'soundl3.bas', 'beschrijving', 1),
    array(47, 0, 'mm23intr.txt', 'beschrijving', 1),
    array(47, 0, 'pinb2.bas', 'beschrijving', 1),
    array(47, 0, 'tl.com', 'beschrijving', 1),
    array(47, 0, 'autotx', 'beschrijving', 1),
    array(47, 0, 'color.tsr', 'beschrijving', 1),
    array(47, 0, 'mengclr.bas', 'beschrijving', 1),
    array(47, 0, 'autoexe1', 'beschrijving', 1),
    array(47, 0, 'autoexe2', 'beschrijving', 1),
    array(47, 0, 'showpic.bas', 'beschrijving', 1),
    array(47, 0, 'autoexec.cop', 'beschrijving', 1),
    array(47, 0, 'memman.com', 'beschrijving', 1),
    array(47, 0, 'soundl5.bas', 'beschrijving', 1),
    array(47, 0, 'memman.bin', 'beschrijving', 1),
    array(47, 0, 'pinb3.bas', 'beschrijving', 1),
    array(47, 0, 'cfgmman.com', 'beschrijving', 1),
    array(47, 0, 'soundl7.bas', 'beschrijving', 1),
    array(47, 0, 'hspel1.s12', 'beschrijving', 1),
    array(47, 0, 'disknaam.bas', 'beschrijving', 1),
    array(47, 0, 'scroll.bas', 'beschrijving', 1),
    array(47, 0, 'icp7', 'beschrijving', 1),
    array(47, 0, 'testbld.s12', 'beschrijving', 1),
    array(47, 0, 'pinb1.bas', 'beschrijving', 1),
    array(47, 0, 'icp7.bin', 'beschrijving', 1),
    array(47, 0, 'tv.com', 'beschrijving', 1),
    array(48, 0, 'lasergun', 'beschrijving', 1),
    array(48, 0, 'icp7tsr.bas', 'beschrijving', 1),
    array(48, 0, 'showem', 'beschrijving', 1),
    array(48, 0, 'elitesav', 'beschrijving', 1),
    array(48, 0, 'mem3l2.asc', 'beschrijving', 1),
    array(48, 0, 'autotx', 'beschrijving', 1),
    array(48, 0, 'autoexe1', 'beschrijving', 1),
    array(48, 0, 'autoexe2', 'beschrijving', 1),
    array(48, 0, 'autoexec.cop', 'beschrijving', 1),
    array(48, 0, 'cnvgif', 'beschrijving', 1),
    array(48, 0, 'kikkr.gif', 'beschrijving', 1),
    array(48, 0, 'icp7.tsr', 'beschrijving', 1),
    array(48, 0, 'lips.gif', 'beschrijving', 1),
    array(48, 0, 'elitecht', 'beschrijving', 1),
    array(48, 0, 'gtslt2.asc', 'beschrijving', 1),
    array(48, 0, 'calsub.asc', 'beschrijving', 1),
    array(48, 0, 'enaram.asc', 'beschrijving', 1),
    array(48, 0, 'icp7', 'beschrijving', 1),
    array(48, 0, 'showem.com', 'beschrijving', 1),
    array(48, 0, 'icp7.bin', 'beschrijving', 1),
    array(49, 0, 'mobius', 'beschrijving', 1),
    array(49, 0, 'cdtje2', 'beschrijving', 1),
    array(49, 0, 'zas6l1.asc', 'beschrijving', 1),
    array(49, 0, 'dorelk2', 'beschrijving', 1),
    array(49, 0, 'ehbo', 'beschrijving', 1),
    array(49, 0, 'cdtje', 'beschrijving', 1),
    array(49, 0, 'cdtje1', 'beschrijving', 1),
    array(49, 0, 'tk.com', 'beschrijving', 1),
    array(49, 0, 'mm23spec.txt', 'beschrijving', 1),
    array(49, 0, 'vlkrl', 'beschrijving', 1),
    array(49, 0, 'mm23intr.txt', 'beschrijving', 1),
    array(49, 0, '4096-2', 'beschrijving', 1),
    array(49, 0, 'onmog', 'beschrijving', 1),
    array(49, 0, 'russia', 'beschrijving', 1),
    array(49, 0, 'tl.com', 'beschrijving', 1),
    array(49, 0, 'autotx', 'beschrijving', 1),
    array(49, 0, 'autoexe1', 'beschrijving', 1),
    array(49, 0, 'autoexe2', 'beschrijving', 1),
    array(49, 0, 'cdtjec', 'beschrijving', 1),
    array(49, 0, 'autoexec.cop', 'beschrijving', 1),
    array(49, 0, 'palette', 'beschrijving', 1),
    array(49, 0, 'memman.com', 'beschrijving', 1),
    array(49, 0, 'memman.bin', 'beschrijving', 1),
    array(49, 0, 'zas6l2.asc', 'beschrijving', 1),
    array(49, 0, 'mem4l1.asm', 'beschrijving', 1),
    array(49, 0, 'cfgmman.com', 'beschrijving', 1),
    array(49, 0, 'dsktst', 'beschrijving', 1),
    array(49, 0, 'mmdemo.asc', 'beschrijving', 1),
    array(49, 0, 'dorelk', 'beschrijving', 1),
    array(49, 0, 'icp7', 'beschrijving', 1),
    array(49, 0, 'rond', 'beschrijving', 1),
    array(49, 0, 'icp7.bin', 'beschrijving', 1),
    array(49, 0, 'tv.com', 'beschrijving', 1),
    array(49, 0, '4096-2.asc', 'beschrijving', 1),
    array(50, 0, 'sampblk1.smp', 'beschrijving', 1),
    array(50, 0, 'piplin', 'beschrijving', 1),
    array(50, 0, 'mse.bas', 'beschrijving', 1),
    array(50, 0, 'pucky2.m1m', 'beschrijving', 1),
    array(50, 0, 'pucky.ldr', 'beschrijving', 1),
    array(50, 0, 'pucky.asc', 'beschrijving', 1),
    array(50, 0, 'rubik1', 'beschrijving', 1),
    array(50, 0, 'boom', 'beschrijving', 1),
    array(50, 0, 'boom2', 'beschrijving', 1),
    array(50, 0, 'rubiklok', 'beschrijving', 1),
    array(50, 0, 'autotx', 'beschrijving', 1),
    array(50, 0, 'piano', 'beschrijving', 1),
    array(50, 0, 'pucky2.m2m', 'beschrijving', 1),
    array(50, 0, 'sampblk3.smp', 'beschrijving', 1),
    array(50, 0, 'pipmak', 'beschrijving', 1),
    array(50, 0, 'autoexe1', 'beschrijving', 1),
    array(50, 0, 'autoexe2', 'beschrijving', 1),
    array(50, 0, 'mcbc2l1.asc', 'beschrijving', 1),
    array(50, 0, 'bal2', 'beschrijving', 1),
    array(50, 0, 'autoexec.cop', 'beschrijving', 1),
    array(50, 0, 'mcbc2l3', 'beschrijving', 1),
    array(50, 0, 'mcbc2l2', 'beschrijving', 1),
    array(50, 0, 'pucky', 'beschrijving', 1),
    array(50, 0, 'pucky.m2m', 'beschrijving', 1),
    array(50, 0, 'bal', 'beschrijving', 1),
    array(50, 0, 'mseldr', 'beschrijving', 1),
    array(50, 0, 'hap', 'beschrijving', 1),
    array(50, 0, 'pucky.m1m', 'beschrijving', 1),
    array(50, 0, 'sampblk2.smp', 'beschrijving', 1),
    array(50, 0, 'pipefigs.pic', 'beschrijving', 1),
    array(50, 0, 'icp7', 'beschrijving', 1),
    array(50, 0, 'samptr', 'beschrijving', 1),
    array(50, 0, 'icp7.bin', 'beschrijving', 1),
    array(50, 0, 'kerst', 'beschrijving', 1),
    array(50, 0, 'pucky.bas', 'beschrijving', 1),
    array(51, 0, 'interru.asc', 'beschrijving', 1),
    array(51, 0, 'turbbas4', 'beschrijving', 1),
    array(51, 0, 'mmpatch.bas', 'beschrijving', 1),
    array(51, 0, 'msxdos.sys', 'beschrijving', 1),
    array(51, 0, 'mididr', 'beschrijving', 1),
    array(51, 0, 'bpunch.lzh', 'beschrijving', 1),
    array(51, 0, 'tk.com', 'beschrijving', 1),
    array(51, 0, 'mm23spec.txt', 'beschrijving', 1),
    array(51, 0, 'ansinit', 'beschrijving', 1),
    array(51, 0, 'caps.tsr', 'beschrijving', 1),
    array(51, 0, 'tv.bas', 'beschrijving', 1),
    array(51, 0, 'pmext220.com', 'beschrijving', 1),
    array(51, 0, 'silent', 'beschrijving', 1),
    array(51, 0, 'pmarc200.pma', 'beschrijving', 1),
    array(51, 0, 'mm23intr.txt', 'beschrijving', 1),
    array(51, 0, 'turbbas3', 'beschrijving', 1),
    array(51, 0, 'nosys.ldr', 'beschrijving', 1),
    array(51, 0, 'usas', 'beschrijving', 1),
    array(51, 0, 'tl.com', 'beschrijving', 1),
    array(51, 0, 'autotx', 'beschrijving', 1),
    array(51, 0, 'color.tsr', 'beschrijving', 1),
    array(51, 0, 'autotx.txt', 'beschrijving', 1),
    array(51, 0, 'bin2dec', 'beschrijving', 1),
    array(51, 0, 'autoexe1', 'beschrijving', 1),
    array(51, 0, 'autoexe2', 'beschrijving', 1),
    array(51, 0, 'turbbas1', 'beschrijving', 1),
    array(51, 0, 'autoexec.cop', 'beschrijving', 1),
    array(51, 0, 'command.com', 'beschrijving', 1),
    array(51, 0, 'memman.com', 'beschrijving', 1),
    array(51, 0, 'memman.bin', 'beschrijving', 1),
    array(51, 0, 'mozart', 'beschrijving', 1),
    array(51, 0, 'bk-man.txt', 'beschrijving', 1),
    array(51, 0, 'pakuit.bat', 'beschrijving', 1),
    array(51, 0, 'diskdi4.bas', 'beschrijving', 1),
    array(51, 0, 'cfgmman.com', 'beschrijving', 1),
    array(51, 0, 'tlpatch.bas', 'beschrijving', 1),
    array(51, 0, 'turbbas2', 'beschrijving', 1),
    array(51, 0, 'gios.asc', 'beschrijving', 1),
    array(51, 0, 'bk.com', 'beschrijving', 1),
    array(51, 0, 'icp7', 'beschrijving', 1),
    array(51, 0, 'schuif', 'beschrijving', 1),
    array(51, 0, 'icp7.bin', 'beschrijving', 1),
    array(51, 0, 'nosys.com', 'beschrijving', 1),
    array(51, 0, 'tv.com', 'beschrijving', 1),
    array(51, 0, 'dec2bin', 'beschrijving', 1),
    array(51, 0, 'ptpma.pma', 'beschrijving', 1),
    array(51, 0, 'ansi', 'beschrijving', 1),
    array(52, 0, 'gans2.pic', 'beschrijving', 1),
    array(52, 0, 'mmpatch.bas', 'beschrijving', 1),
    array(52, 0, 'diashw', 'beschrijving', 1),
    array(52, 0, 'mousor.bas', 'beschrijving', 1),
    array(52, 0, 'salber', 'beschrijving', 1),
    array(52, 0, 'tk.com', 'beschrijving', 1),
    array(52, 0, 'filvr2', 'beschrijving', 1),
    array(52, 0, 'molastig.ldr', 'beschrijving', 1),
    array(52, 0, 'web', 'beschrijving', 1),
    array(52, 0, 'filvr2.bin', 'beschrijving', 1),
    array(52, 0, 'mm23spec.txt', 'beschrijving', 1),
    array(52, 0, 'caps.tsr', 'beschrijving', 1),
    array(52, 0, 'cant.pic', 'beschrijving', 1),
    array(52, 0, 'tv.bas', 'beschrijving', 1),
    array(52, 0, 'icp7.bas', 'beschrijving', 1),
    array(52, 0, 'filvr1.bin', 'beschrijving', 1),
    array(52, 0, 'mm23intr.txt', 'beschrijving', 1),
    array(52, 0, 'bloemen.pic', 'beschrijving', 1),
    array(52, 0, 'olympic', 'beschrijving', 1),
    array(52, 0, 'molastig.bin', 'beschrijving', 1),
    array(52, 0, 'tl.com', 'beschrijving', 1),
    array(52, 0, 'autotx', 'beschrijving', 1),
    array(52, 0, 'gans.pic', 'beschrijving', 1),
    array(52, 0, 'prtusr.bin', 'beschrijving', 1),
    array(52, 0, 'color.tsr', 'beschrijving', 1),
    array(52, 0, 'autoexe1', 'beschrijving', 1),
    array(52, 0, 'autoexe2', 'beschrijving', 1),
    array(52, 0, 'autoexec.cop', 'beschrijving', 1),
    array(52, 0, 'draai', 'beschrijving', 1),
    array(52, 0, 'memman.com', 'beschrijving', 1),
    array(52, 0, 'filvr1.asm', 'beschrijving', 1),
    array(52, 0, 'mousor.tsr', 'beschrijving', 1),
    array(52, 0, 'memman.bin', 'beschrijving', 1),
    array(52, 0, 'prtusr', 'beschrijving', 1),
    array(52, 0, 'stralen', 'beschrijving', 1),
    array(52, 0, 'cfgmman.com', 'beschrijving', 1),
    array(52, 0, 'molastig', 'beschrijving', 1),
    array(52, 0, 'draai2', 'beschrijving', 1),
    array(52, 0, 'prtusr.asm', 'beschrijving', 1),
    array(52, 0, 'vrbld', 'beschrijving', 1),
    array(52, 0, 'filvr2.asm', 'beschrijving', 1),
    array(52, 0, 'tikdit', 'beschrijving', 1),
    array(52, 0, 'icp7.bin', 'beschrijving', 1),
    array(52, 0, 'tv.com', 'beschrijving', 1),
    array(52, 0, 'web2', 'beschrijving', 1),
    array(52, 0, 'molas', 'beschrijving', 1),
    array(53, 0, 'brug.pic', 'beschrijving', 1),
    array(53, 0, 'game.asc', 'beschrijving', 1),
    array(53, 0, 'diashw', 'beschrijving', 1),
    array(53, 0, 'memview.tsr', 'beschrijving', 1),
    array(53, 0, 'sftreset.tsr', 'beschrijving', 1),
    array(53, 0, 'switch1.bin', 'beschrijving', 1),
    array(53, 0, 'game.c', 'beschrijving', 1),
    array(53, 0, 'q8', 'beschrijving', 1),
    array(53, 0, 'uitleg.wp', 'beschrijving', 1),
    array(53, 0, 'midibios.inc', 'beschrijving', 1),
    array(53, 0, 'mididr.gen', 'beschrijving', 1),
    array(53, 0, 'switch2.bin', 'beschrijving', 1),
    array(53, 0, 'autotx', 'beschrijving', 1),
    array(53, 0, '5060hz.tsr', 'beschrijving', 1),
    array(53, 0, 'autoexe1', 'beschrijving', 1),
    array(53, 0, 'autoexe2', 'beschrijving', 1),
    array(53, 0, 'ice.pic', 'beschrijving', 1),
    array(53, 0, 'autoexec.cop', 'beschrijving', 1),
    array(53, 0, 'contrl.bas', 'beschrijving', 1),
    array(53, 0, 'lantern.pic', 'beschrijving', 1),
    array(53, 0, 'devildog.sc5', 'beschrijving', 1),
    array(53, 0, 'chgcpu.tsr', 'beschrijving', 1),
    array(53, 0, 'switch1.bas', 'beschrijving', 1),
    array(53, 0, 'mididr.bin', 'beschrijving', 1),
    array(53, 0, 'toon5', 'beschrijving', 1),
    array(53, 0, 'switch2.bas', 'beschrijving', 1),
    array(53, 0, 'switch', 'beschrijving', 1),
    array(53, 0, 'mididr.ldr', 'beschrijving', 1),
    array(53, 0, 'game.mac', 'beschrijving', 1),
    array(53, 0, 'icp7', 'beschrijving', 1),
    array(53, 0, 'makegame.bat', 'beschrijving', 1),
    array(53, 0, 'game.bin', 'beschrijving', 1),
    array(53, 0, 'icp7.bin', 'beschrijving', 1),
    array(53, 0, 'mask.pic', 'beschrijving', 1),
    array(54, 0, 'synpar1.txt', 'beschrijving', 1),
    array(54, 0, 'diashw', 'beschrijving', 1),
    array(54, 0, 'klelog', 'beschrijving', 1),
    array(54, 0, 'balk-in1', 'beschrijving', 1),
    array(54, 0, 'midiklav.tsr', 'beschrijving', 1),
    array(54, 0, 'supdel', 'beschrijving', 1),
    array(54, 0, 'scr0inst.bas', 'beschrijving', 1),
    array(54, 0, 'icp7.bas', 'beschrijving', 1),
    array(54, 0, 'klokje', 'beschrijving', 1),
    array(54, 0, 'playsmp1.com', 'beschrijving', 1),
    array(54, 0, 'viool.pic', 'beschrijving', 1),
    array(54, 0, 'autotx', 'beschrijving', 1),
    array(54, 0, 'autoexe1', 'beschrijving', 1),
    array(54, 0, 'autoexe2', 'beschrijving', 1),
    array(54, 0, 'butfly.bas', 'beschrijving', 1),
    array(54, 0, 'butter7.fly', 'beschrijving', 1),
    array(54, 0, 'kortst', 'beschrijving', 1),
    array(54, 0, 'patroon', 'beschrijving', 1),
    array(54, 0, 'klokje2', 'beschrijving', 1),
    array(54, 0, 'autoexec.cop', 'beschrijving', 1),
    array(54, 0, 'dancenow.pck', 'beschrijving', 1),
    array(54, 0, 'vlieger.pic', 'beschrijving', 1),
    array(54, 0, 'patro2a', 'beschrijving', 1),
    array(54, 0, 'supdel2', 'beschrijving', 1),
    array(54, 0, 'patro2b', 'beschrijving', 1),
    array(54, 0, 'synpar1.src', 'beschrijving', 1),
    array(54, 0, 'synpar1.com', 'beschrijving', 1),
    array(54, 0, 'balk', 'beschrijving', 1),
    array(54, 0, '65536!', 'beschrijving', 1),
    array(54, 0, 'reformed.pck', 'beschrijving', 1),
    array(54, 0, 'synpar1.bas', 'beschrijving', 1),
    array(54, 0, 'icp7.bin', 'beschrijving', 1),
    array(54, 0, 'fonts.tsr', 'beschrijving', 1),
    array(54, 0, 'scr0dump.tsr', 'beschrijving', 1),
    array(54, 0, 'scr0dump.bas', 'beschrijving', 1),
    array(54, 0, 'supdel2a', 'beschrijving', 1),
    array(55, 10, 'trap', 'Recursie: ook in Basic! Trapprobleem', 1),
    array(55, 11, 'dec-bin', 'Recursie: ook in Basic! Decimaal naar binair', 1),
    array(55, 11, 'haakjes', 'Recursie: ook in Basic! Haakjes checken', 1),
    array(55, 0, 'bin-dec', 'Recursie: ook in Basic! Binair naar decimaal', 1),
    array(55, 0, 'facul', 'Recursie: ook in Basic! Berekent X-faculteit', 1),
    array(55, 0, 'fibo', 'Recursie: ook in Basic! Geeft reeks van Fibonacci', 1),
    array(55, 0, 'ggd', 'Recursie: ook in Basic! Berekent de Grootste Gemene Deler', 1),
    array(55, 0, 'hanoi', 'Recursie: ook in Basic! Lost torens van Hanoi op', 1),
    array(55, 0, 'macht1', 'Recursie: ook in Basic! Berekent X^Y op domme manier', 1),
    array(55, 0, 'macht2', 'Recursie: ook in Basic! Berekent X^Y op slimme manier', 1),
    array(55, 0, 'pascal', 'Recursie: ook in Basic! Geeft regel uit driehoek van Pascal', 1),
    array(55, 0, 'paus', 'Recursie: ook in Basic! Paus-namen: Johannes Paulus', 1),
    array(55, 0, 'priemfac', 'Recursie: ook in Basic! Deelt een getal op in priemfactoren', 1),
    array(55, 0, 'priemlst', 'Recursie: ook in Basic! Geeft lijst priemgetallen', 1),
    array(55, 0, 'priemtst', 'Recursie: ook in Basic! Test of een getal priem is', 1),
    array(55, 0, 'som1', 'Recursie: ook in Basic! Berekent som van getallen uit interval', 1),
    array(55, 0, 'som2', 'Recursie: ook in Basic! Berekent som der cijfers der cijfers...', 1),
    array(55, 0, 'tafel', 'Recursie: ook in Basic! Drukt tafel van een getal af', 1),
    array(56, 0, 'slide2.prg', 'beschrijving', 1),
    array(56, 0, 'runani.bas', 'beschrijving', 1),
    array(56, 0, 'msxpaint.iv', 'beschrijving', 1),
    array(56, 0, 'master1', 'beschrijving', 1),
    array(56, 0, 'midiint3.bin', 'beschrijving', 1),
    array(56, 0, 'standard.fn7', 'beschrijving', 1),
    array(56, 0, 'standard.fn5', 'beschrijving', 1),
    array(56, 0, 'standard.br8', 'beschrijving', 1),
    array(56, 0, 'standard.pt7', 'beschrijving', 1),
    array(56, 0, 'standard.br7', 'beschrijving', 1),
    array(56, 0, 'doolhof.asc', 'beschrijving', 1),
    array(56, 0, 'standard.pt6', 'beschrijving', 1),
    array(56, 0, 'rotate.prg', 'beschrijving', 1),
    array(56, 0, 'menu.prg', 'beschrijving', 1),
    array(56, 0, 'slide3.prg', 'beschrijving', 1),
    array(56, 0, 'midiint1.gen', 'beschrijving', 1),
    array(56, 0, 'dtm.prg', 'beschrijving', 1),
    array(56, 0, 'digitize.prg', 'beschrijving', 1),
    array(56, 0, 'standard.fn6', 'beschrijving', 1),
    array(56, 0, 'disk.prg', 'beschrijving', 1),
    array(56, 0, 'master2', 'beschrijving', 1),
    array(56, 0, 'midi-int', 'beschrijving', 1),
    array(56, 0, 'midi-int.bas', 'beschrijving', 1),
    array(56, 0, 'slide1.prg', 'beschrijving', 1),
    array(56, 0, 'standard.pt8', 'beschrijving', 1),
    array(56, 0, 'icp7.bas', 'beschrijving', 1),
    array(56, 0, 'brush.prg', 'beschrijving', 1),
    array(56, 0, 'mcmbase', 'beschrijving', 1),
    array(56, 0, 'flycreep.cc7', 'beschrijving', 1),
    array(56, 0, 'midiint1.bin', 'beschrijving', 1),
    array(56, 0, 'diskedit.prg', 'beschrijving', 1),
    array(56, 0, 'midiint2.gen', 'beschrijving', 1),
    array(56, 0, 'midiint4.bin', 'beschrijving', 1),
    array(56, 0, 'draw.prg', 'beschrijving', 1),
    array(56, 0, 'cacahu.sc8', 'beschrijving', 1),
    array(56, 0, 'videotex.prg', 'beschrijving', 1),
    array(56, 0, 'copy.prg', 'beschrijving', 1),
    array(56, 0, 'sel-mode.prg', 'beschrijving', 1),
    array(56, 0, 'diskcopy.prg', 'beschrijving', 1),
    array(56, 0, 'doozle.obj', 'beschrijving', 1),
    array(56, 0, 'midiint4.gen', 'beschrijving', 1),
    array(56, 0, 'brothers.cc7', 'beschrijving', 1),
    array(56, 0, 'midiint3.gen', 'beschrijving', 1),
    array(56, 0, 'ehbol1', 'beschrijving', 1),
    array(56, 0, 'print.prg', 'beschrijving', 1),
    array(56, 0, '3d.prg', 'beschrijving', 1),
    array(56, 0, 'sprites5.spr', 'beschrijving', 1),
    array(56, 0, 'standard.br6', 'beschrijving', 1),
    array(56, 0, 'wolfmuti.cc7', 'beschrijving', 1),
    array(56, 0, 'msxpnt2.bin', 'beschrijving', 1),
    array(56, 0, 'midimuis.bas', 'beschrijving', 1),
    array(56, 0, 'fonted.prg', 'beschrijving', 1),
    array(56, 0, 'standard.fn8', 'beschrijving', 1),
    array(56, 0, 'doozle.bas', 'beschrijving', 1),
    array(56, 0, 'doozle.dat', 'beschrijving', 1),
    array(56, 0, 'standard.pt5', 'beschrijving', 1),
    array(56, 0, 'midiint2.bin', 'beschrijving', 1),
    array(56, 0, 'midicur5.txt', 'beschrijving', 1),
    array(56, 0, 'ramcopy.bin', 'beschrijving', 1),
    array(56, 0, 'msxpnt1.bin', 'beschrijving', 1),
    array(56, 0, 'sprites.spr', 'beschrijving', 1),
    array(56, 0, 'icp7.bin', 'beschrijving', 1),
    array(56, 0, 'animate.prg', 'beschrijving', 1),
    array(56, 0, 'paintiv.st8', 'beschrijving', 1),
    array(56, 0, 'standard.br5', 'beschrijving', 1),
/** Autoexec start-up/menu files
    array(56, 0, 'autotx', 'beschrijving', 1),
    array(56, 0, 'autoexe1', 'beschrijving', 1),
    array(56, 0, 'autoexe2', 'beschrijving', 1),
    array(56, 0, 'autoexec.cop', 'beschrijving', 1),
*/
    array(57, 6, 'vbc1', 'Bestanden op cassette, voorbeeld 1', 1),
    array(57, 7, 'vbc2', 'Bestanden op cassette, voorbeeld 2', 1),
    array(57, 7, 'vbc3', 'Bestanden op cassette, voorbeeld 3', 1),
    array(57, 8, 'vbc4', 'Bestanden op cassette, voorbeeld 4', 1),
    array(57, 8, 'vbc5', 'Bestanden op cassette, voorbeeld 5', 1),
    array(57, 8, 'vbc6', 'Bestanden op cassette, voorbeeld 6', 1),
    array(57, 9, 'vbc7', 'Bestanden op cassette, voorbeeld 7', 1),
    array(57, 9, 'vbc8', 'Bestanden op cassette, voorbeeld 8', 1),
    array(57, 11, 'fplot', 'MCM\'s functietekenaar', 1),
    array(57, 52, 'sneeuw', 'Sneeuw (K&K57-1)', 2),
    array(57, 52, 'sneeuw2', 'Sneeuw 2 (K&K57-1a)', 2),
    array(57, 53, 'kerst1', 'Kerst 1 (K&K57-2a)', 1),
    array(57, 53, 'kerst2', 'Kerst 2 (K&K57-2b)', 2),
    array(57, 53, 'mcm', 'MCM (K&K57-3)', 2),
    array(57, 54, 'twdgrds', 'Tweedegraads vergelijkingen (K&K57-4)', 1),
    array(57, 54, 'balk2', 'Balk 2 (K&K 57-5)', 3),
    array(57, 55, 'prntxt1', 'Print Tekst 1 voor MSX printers (K&K 57-6a)', 1),
    array(57, 55, 'prntxt2', 'Print Tekst 2 voor niet-MSX printers (K&K 57-6b)', 1),
    array(57, 55, 'wanwan', 'Wanwanliner (K&K57-7)', 2),
    array(57, 65, 'icp7', 'ICP/7 generator', 1),
    array(57, 0, 'icp7.bin', 'ICP/7', 1),
/** Art Gallery files */
    array(57, 0, 'diashw', 'Diashow', 2),
    array(57, 0, 'darkness', 'Instrument of Darkness intro', 2),
    array(57, 0, 'darkness.001', 'Instrument of Darkness 1', 2),
    array(57, 0, 'darkness.002', 'Instrument of Darkness 2', 2),
    array(57, 0, 'futcity.bas', 'Future City loader', 1),
    array(57, 0, 'futcity.ge5', 'Future City (?)', 2),
    array(57, 0, 'panda.pic', 'Panda', 2),
    array(57, 0, 'runner.ge5', 'Runner', 2),
/** MemMan 2.4.2 files */
    array(57, 0, 'bk104man.txt', '', 1),
    array(57, 0, 'memman.com', '', 2),
    array(57, 0, 'memman.bin', '', 2),
    array(57, 0, 'mm24spec.txt', '', 1),
    array(57, 0, 'mm24intr.txt', '', 1),
    array(57, 0, 'color.tsr', '', 2),
    array(57, 0, 'cfgmman.com', '', 2),
    array(57, 0, 'bk.com', '', 2),
    array(57, 0, 'show', '', 2),
    array(57, 0, 'tv', '', 2),
    array(57, 0, 'tv.com', '', 2),
    array(57, 0, 'testmman.com', '', 2),
    array(57, 0, 'tk.com', '', 2),
    array(57, 0, 'tl.com', '', 2),
    array(57, 0, 'caps.tsr', '', 2)
/** Autoexec start-up/menu files
    array(57, 0, 'autotx', '', 1),
    array(57, 0, 'autoexec', '', 1),
    array(57, 0, 'autoexe1', '', 1),
    array(57, 0, 'autoexe2', '', 1),
    array(57, 0, 'autoexec.cop', '', 1),
*/
);


?>
